# Generated by Django 3.2.19 on 2023-07-06 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_ingredient_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeIngredients',
            new_name='IngredientInRecipe',
        ),
    ]
